# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webform',
            name='affiliation',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='webform',
            name='request_body',
            field=models.TextField(max_length=2000),
        ),
    ]
