# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='person',
            field=models.ForeignKey(default=593, on_delete=django.db.models.deletion.CASCADE, to='directory.DepartmentMember'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='quarter',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, to='courses.Quarter'),
        ),
    ]
