# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_auto_20180427_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=b'')),
                ('video_link', models.URLField()),
                ('courses', models.ManyToManyField(to='courses.Course')),
            ],
        ),
    ]
