# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asset',
            new_name='Demonstration',
        ),
    ]
