# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0002_auto_20180502_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demonstration',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/demos/'),
        ),
        migrations.AlterField(
            model_name='demonstration',
            name='video_link',
            field=models.URLField(blank=True),
        ),
    ]
