# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 13:27
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0003_auto_20180502_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demonstration',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=b'JPEG', keep_meta=True, quality=75, size=[700, 500], upload_to='uploads/demos/'),
        ),
    ]
