# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0005_auto_20180508_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demonstration',
            name='video_link',
            field=models.TextField(blank=True, help_text='paste the entire youtube embed text in this box. '),
        ),
    ]
